import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { DemoCase, formatRupees, LEDGER } from "@/lib/domain";

const styles = StyleSheet.create({
  page: { padding: 42, fontSize: 10, color: "#18322b", fontFamily: "Helvetica" },
  brand: { fontSize: 19, fontFamily: "Helvetica-Bold", color: "#0b806e", marginBottom: 8 },
  eyebrow: { fontSize: 8, color: "#60746c", marginBottom: 22 },
  title: { fontSize: 23, fontFamily: "Helvetica-Bold", marginBottom: 10 },
  note: { color: "#496157", lineHeight: 1.55, marginBottom: 18 },
  block: { borderWidth: 1, borderColor: "#dce4dc", padding: 13, borderRadius: 5, marginBottom: 13 },
  label: { fontSize: 8, color: "#60746c", marginBottom: 3 },
  amount: { fontSize: 22, fontFamily: "Helvetica-Bold", color: "#0b806e" },
  event: { marginBottom: 8 },
  eventTitle: { fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 30, left: 42, right: 42, color: "#60746c", fontSize: 8 },
});

function SummaryDocument({ caseData }: { caseData: DemoCase }) {
  return <Document title="EPFO Resolve — Synthetic resolution summary"><Page size="A4" style={styles.page}>
    <Text style={styles.brand}>EPFO Resolve</Text><Text style={styles.eyebrow}>INDEPENDENT SYNTHETIC HACKATHON PROTOTYPE · NOT AN OFFICIAL EPFO RECORD</Text>
    <Text style={styles.title}>Ananya Rao — resolution summary</Text>
    <Text style={styles.note}>This document records a fictional demonstration only. No real transfer, identity verification, employer communication, EPFO action, or financial movement occurred.</Text>
    <View style={styles.block}><Text style={styles.label}>SIMULATED TRANSFER STATUS</Text><Text>{caseData.status === "transfer_completed" ? "Completed" : "Correction and reconciliation ready"}</Text></View>
    <View style={styles.block}><Text style={styles.label}>RECONCILED SYNTHETIC AMOUNT</Text><Text style={styles.amount}>{formatRupees(LEDGER.total)}</Text><Text>EPS reclassification: {formatRupees(LEDGER.before.eps)} moved to EPF; total value remains unchanged.</Text></View>
    <View style={styles.block}><Text style={styles.label}>CORRECTION RATIONALE</Text><Text>Fictional case facts: first membership after 01 Sep 2014, Basic + DA ₹18,500, no prior EPS membership, and an incorrectly recorded EPS entry. Source used in the prototype: EPFO FAQ.</Text></View>
    <Text style={{ ...styles.label, marginBottom: 8 }}>AUDIT HISTORY</Text>{caseData.events.map((event) => <View key={event.id} style={styles.event}><Text style={styles.eventTitle}>{event.date} · {event.title}</Text><Text>{event.actor}: {event.description}</Text></View>)}
    <Text style={styles.footer}>Generated by EPFO Resolve · Synthetic data only · https://www.epfindia.gov.in/site_en/FAQ.php</Text>
  </Page></Document>;
}

export async function renderResolutionPdf(caseData: DemoCase) { return renderToBuffer(<SummaryDocument caseData={caseData} />); }
